python3 example_use.py \
    --bert_path ckpt/batch_any \
    --train_data train \
    --dev_data dev \
    --train_batch_size 128\
    --lr 2e-5\
    --dropout 0.1\
    --print_every 100 \
    --eval_every 10000\
    --gpu_id 1\
    --fine_tune
