python3 train_dist.py --embed_dim 768 \
                      --ff_embed_dim 3072 \
                      --num_heads 12 \
                      --layers 12 \
                      --dropout 0.1 \
                      --train_data tmp\
                      --vocab tmp_vocab\
                      --batch_size 32\
                      --max_len 256 \
                      --world_size 8\
                      --gpus 8\
                      --MASTER_ADDR 100.88.66.72\
                      --MASTER_PORT 29500\
                      --start_rank 0\
                      --print_every 100\
                      --save_every 1000
